services:
  - type: web
    name: mamabear-backend
    runtime: docker
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: APP_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: MIDTRANS_SERVER_KEY
        sync: false
      - key: MIDTRANS_CLIENT_KEY
        sync: false
      - key: MIDTRANS_IS_PRODUCTION
        value: "false"
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: RAJAONGKIR_API_KEY
        sync: false
      - key: XENDIT_SECRET_KEY
        sync: false
